#!/bin/sh
# Written by rpi-image-gen layer mp-hmi-proxy: the panel's origins follow its
# addresses and its hostname.
case $2 in
   up | down | dhcp4-change | hostname) exec /usr/sbin/mp-hmi-origins ;;
esac
exit 0
