# Written by rpi-image-gen layer mp-hmi-proxy: haproxy reads the origin list
# and the update flag when it starts.
[Unit]
Wants=mp-hmi-origins.service mp-hmi-ota-state.service
After=mp-hmi-origins.service mp-hmi-ota-state.service
